spring:
  datasource:
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 120m
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  config: classpath:spring/spring-logback.xml
