spring:
  datasource:
    write:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://db-colosseum-cluster.cluster-cnlzrndairv2.ap-northeast-2.rds.amazonaws.com:3306/colo_edu?characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: edu_dev
      password: edu2107!
      maximum-pool-size: 3
    read:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://db-colosseum-cluster.cluster-cnlzrndairv2.ap-northeast-2.rds.amazonaws.com:3306/colo_edu?characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: edu_dev
      password: edu2107!
      maximum-pool-size: 3

logging.dir: ${logs.dir}
